### ISSUE TITLE
Problematic example

### ISSUE THREAD

**Issue by ymyke** [tarioch/xirr#13]
Here's an interesting example of numbers:

Values:

```
[5046.0, 5037.299999999999, 4995.25, 5795.5, -1085.6, 4998.0, 4557.8, 4815.0, 4928.0, -2197.05, 5424.0, -2565.0, -2872.8, 10085.0, 9500.0, 9976.8, 14880.000000000002, -6094.7, 19522.359999999997, 18035.0, 10477.44]
```

Dates:

```
[Timestamp('2015-08-03 00:00:00+0000', tz='UTC'), Timestamp('2015-10-20 00:00:00+0000', tz='UTC'), Timestamp('2016-01-11 00:00:00+0000', tz='UTC'), Timestamp('2016-04-06 00:00:00+0000', tz='UTC'), Timestamp('2016-04-26 00:00:00+0000', tz='UTC'), Timestamp('2016-07-19 00:00:00+0000', tz='UTC'), Timestamp('2016-10-11 00:00:00+0000', tz='UTC'), Timestamp('2017-01-11 00:00:00+0000', tz='UTC'), Timestamp('2017-04-11 00:00:00+0000', tz='UTC'), Timestamp('2017-04-25 00:00:00+0000', tz='UTC'), Timestamp('2017-10-12 00:00:00+0000', tz='UTC'), Timestamp('2018-04-24 00:00:00+0000', tz='UTC'), Timestamp('2019-04-23 00:00:00+0000', tz='UTC'), Timestamp('2020-02-25 00:00:00+0000', tz='UTC'), Timestamp('2020-03-03 00:00:00+0000', tz='UTC'), Timestamp('2020-03-09 00:00:00+0000', tz='UTC'), Timestamp('2020-04-06 00:00:00+0000', tz='UTC'), Timestamp('2020-04-23 00:00:00+0000', tz='UTC'), Timestamp('2020-06-05 00:00:00+0000', tz='UTC'), Timestamp('2020-08-05 00:00:00+0000', tz='UTC'), Timestamp('2020-08-19 00:00:00+0000', tz='UTC')]
```

It produces an exception in xirr: `ValueError: f(a) and f(b) must have different signs`

It also produces an error in Google Sheets.

Excel, however, produces a result: 

![image](https://user-images.githubusercontent.com/8012482/92327892-26b14d00-f05d-11ea-9bf9-d102c3ed394f.png)

Any idea what is going on here?

**Comment by tarioch** [comment]
just looking at the final result, it looks almost 0 (0.0000000298) I'm guessing that's where it get's really, really tricky.

**Comment by ymyke** [comment]
Yep, that's what I'm thinking too.

**Comment by ymyke** [comment]
Interesting: Increasing maxiter for `brentq` yields a result.

I.e., this `scipy.optimize.brentq(lambda r: utils.mathtools.xnpv(valuesperdate, r), -0.999999999999999, 1e20, maxiter=1000)` yields `-0.9999999779863131`, which makes sense to some extent. That rate does not yield `0`, but `-1620`, which seems to be the optimal solution here apparently.

Excel is way off with its `2.98E-09`. 🤷‍♀️

**Comment by tarioch** [comment]
Interesting, should we increase the maxiter in the library?

**Comment by ymyke** [comment]
Yes, I'd suggest to do so. I'm using `maxiter=10**6` in my local installation. So I suggest to go for something like that.

**Comment by tarioch** [comment]
Can you have a look at #15 and see what numbers I did wrong? The test does still not pass, even with higher maxiter.

**Comment by ymyke** [comment]
Just double-checked: Turns out I somehow mixed up my test data. Please use this data:

Dates:

```
[Timestamp('2016-04-06 00:00:00+0000', tz='UTC'),
 Timestamp('2016-05-04 00:00:00+0000', tz='UTC'),
 Timestamp('2016-05-12 00:00:00+0000', tz='UTC'),
 Timestamp('2017-05-08 00:00:00+0000', tz='UTC'),
 Timestamp('2017-07-03 00:00:00+0000', tz='UTC'),
 Timestamp('2018-05-07 00:00:00+0000', tz='UTC'),
 Timestamp('2019-05-06 00:00:00+0000', tz='UTC'),
 Timestamp('2019-10-01 00:00:00+0000', tz='UTC'),
 Timestamp('2020-03-13 00:00:00+0000', tz='UTC'),
 Timestamp('2020-05-07 00:00:00+0000', tz='UTC'),
 Timestamp('2020-05-07 00:00:00+0000', tz='UTC')]
```

Values:

```
[18902.0,
 83600.0,
 -5780.0,
 -4080.0,
 -56780.0,
 -2210.0,
 -2380.0,
 33975.0,
 23067.98,
 -1619.57,
 -1619.57]
```

Sorry for that!
