### ISSUE TITLE
Type hinting issues

### ISSUE THREAD

**Issue by efseijo** [tarioch/xirr#26]
Should the "dict" and "list" specifications on the type hints be replaced by "Dict" and "List" from the typing module? Python is complaining about these "list" and "dict" hints...

**Comment by efseijo** [comment]
Speaking specifically about xirr.math...

**Comment by tarioch** [comment]
I think dict/list was added with Python 3.9 https://peps.python.org/pep-0585/#id6 on which version of python are you?
It's also possible I'm missing something here.

**Comment by efseijo** [comment]
Ah..
Thanks for the prompt response. 

Yes, you are right. I was using 3.8. I manually made the changes and it worked fine.

Ran it unaltered on 3.9 and it also worked.

Thank you
