### ISSUE TITLE
Minor issues in doctest

### ISSUE THREAD

**Issue by ymyke** [tarioch/xirr#5]
Referencing:
https://github.com/tarioch/xirr/blob/c30b878acea7503acf005ed840d0c4a7e29e39e0/src/xirr/math.py#L36

1. There's one ")" too many at the end.
2. Leading 0s (as in "03") produce a syntax error in Python 3.

Thanks for the lib!

**Comment by tarioch** [comment]
Thanks will try to get this fixed and the build pipeline extended to add doctest to it
