### ISSUE TITLE
Values that fail to calculate

### ISSUE THREAD

**Issue by ymyke** [tarioch/xirr#6]
```python
valuesPerDate = {
        date(2011, 7, 1): 10000,
        date(2014, 7, 1): -1
        }
print(xirr(valuesPerDate))
```
produces:
```python
Traceback (most recent call last):
  File "cmath.py", line 45, in xirr
    result = scipy.optimize.newton(lambda r: xnpv(valuesPerDate, r), 0, maxiter=500)
  File "C:\Users\myken\Anaconda3\lib\site-packages\scipy\optimize\zeros.py", line 340, in newton
    raise RuntimeError(msg)
RuntimeError: Tolerance of -4.2138527602011363e+30 reached. Failed to converge after 5 iterations, value is -4.2138527602012264e+30.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmath.py", line 80, in <module>
    print(xirr(valuesPerDate))
  File "cmath.py", line 47, in xirr
    result = scipy.optimize.brentq(lambda r: xnpv(valuesPerDate, r), -1.0, 1e20)
  File "C:\Users\myken\Anaconda3\lib\site-packages\scipy\optimize\zeros.py", line 775, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs
```

While Google Sheets produces a result:

![image](https://user-images.githubusercontent.com/8012482/88526304-12107c80-cffc-11ea-9067-946709917510.png)

When I flip the signs (as in the second column of the Google Sheet), I also get the correct result with the library:

```python
valuesPerDate = {
        date(2011, 7, 1): -10000,
        date(2014, 7, 1): 1
        }
print(xirr(valuesPerDate))
-0.9534539092750439
```

Any idea what is happening here? (I didn't dive into the mathematics.) Is it a safe approach to just try and flip the signs in case the lib produces a RuntimeError?

**Comment by tarioch** [comment]
Hmm, that's a tricky one, I don't have an answer out of the box.

The base algorithm is coming from https://stackoverflow.com/questions/8919718/financial-python-library-that-has-xirr-and-xnpv-function and I extended it with some of the parts from https://github.com/RayDeCampo/java-xirr/blob/master/src/main/java/org/decampo/xirr/Xirr.java

It's basically running a newton optimization to try to find a rate that matches with the results. There is already a case that if the newton fails, it uses brentq

**Comment by ymyke** [comment]
That is as deep as I grasp the algorithm as well, and I've read the stackoverflow source also.

For my own project I'm currently using:

```python
def my_xirr(valuesPerDate):
    try:
        return xirr(valuesPerDate)
    except (RuntimeError, ValueError):
        return xirr({ d: -v for d, v in valuesPerDate.items() })
```

Not sure if this really makes sense. If it does, it might be worth adding. Or maybe add it as an option to the user, something like a `flippingXirr` method?

**Comment by tarioch** [comment]
Found it. Had a wrong left border for brentq algorithm. This is inclusive borders and it needs to be -0.9999999 instead of -1. With that it works correctly

**Comment by ymyke** [comment]
Nice catch. How did you find out?

**Comment by tarioch** [comment]
Was looking at the fallback algorithm to figure out why it's failing and it mentioned something with not having different signs, then looking at the arguments I got what it's trying.
