### ISSUE TITLE
Add check for all positive / all negative values?

### ISSUE THREAD

**Issue by ymyke** [tarioch/xirr#7]
Referencing:

https://github.com/tarioch/xirr/blob/c30b878acea7503acf005ed840d0c4a7e29e39e0/src/xirr/math.py#L42

Should there be a check there for the extreme cases where all the values have the same sign. I.e., something like this?

```python
    if(all(v >= 0 for _, v in valuesPerDate.items())):
        return -float("inf")
    if(all(v <= 0 for _, v in valuesPerDate.items())):
        return float("inf")
```

**Comment by tarioch** [comment]
I think that makes sense, would you mind creating a PR for it?

**Comment by ymyke** [comment]
Done. My first PR. I hope everything is fine with it.
